ifndef prefix
       prefix=/opt/QCustomPlot/
endif
export prefix

libdir=$(prefix)/lib
includedir=$(prefix)/include

QMAKE=qmake

build: qcustomplot-sharedlib/sharedlib-compilation/Makefile
	(cd qcustomplot-sharedlib/sharedlib-compilation; make)

qcustomplot-sharedlib/sharedlib-compilation/Makefile: qcustomplot-sharedlib/sharedlib-compilation/sharedlib-compilation.pro
	(cd qcustomplot-sharedlib/sharedlib-compilation; qmake)

install: $(libdir)/libqcustomplot.so $(includedir)/qcustomplot.h

$(libdir)/libqcustomplot.so $(includedir)/libqcustomplot.h: qcustomplot-sharedlib/sharedlib-compilation/libqcustomplot.so qcustomplot.h
	- mkdir $(prefix)
	- mkdir $(libdir)
	- mkdir $(includedir)
	cp -P qcustomplot-sharedlib/sharedlib-compilation/libqcustomplot*.so* \
	$(libdir)
	cp qcustomplot.h $(includedir)

qcustomplot-sharedlib/sharedlib-compilation/libqcustomplot.so: build

uninstall:
	- rm -f $(libdir)/libqcustomplot*.so*
	- rm -f $(includedir)/qcustomplot.h
	- rmdir $(libdir)
	- rmdir $(includedir)
	- rmdir $(prefix)

clean:
	- (cd qcustomplot-sharedlib/sharedlib-compilation; make distclean)
